**Known issues:** https://github.com/eliotmcintire/LandWeb/issues (private repository)

--------------------------------------------------------------------------------

### LandWeb v1.0.1

- added axis labels and titles to several figures (#57)
- added text to clarify meaning of "years" in simulations (#58)
- added boxplots that summarize the vegetation cover histograms (#59)
- added news feed and notifications (#60)
- some performance improvements loading maps
- fixed file-naming bug when downloadling model outputs (with #62)
- improved caching
- server upgrades have reduced several performance and disconnection issues

**NOTE:** There appears to be a bias towards deciduous species in some of the results.
This may be due to the interaction between the LandMine fire model and the LANDIS Biomass-Succession models: deciduous species burn less than conifers but regenerate more quickly.
I am currently taking a closer look at the simulations and code to verify these results.

--------------------------------------------------------------------------------

### LandWeb v1.0.0

- time since fire maps, and histograms for all combinations of stand age class, leading vegetation type, and spatial area at a particular patch size;
- vegetation cover histograms for all combinations of stand age class, leading vegetation type, and spatial area;
- user-selectable spatial areas and patch sizes;
- log in using your Google account to view current conditions, upload custom polygons, and download model results.

**NOTE:** There appears to be a bias towards deciduous species in some of the results.
This may be due to the interaction between the LandMine fire model and the LANDIS Biomass-Succession models: deciduous species burn less than conifers but regenerate more quickly.
I am currently taking a closer look at the simulations and code to verify these results.

