if(!require("htmlwidgets")) install.packages("htmlwidgets", dependencies = TRUE) 
if(!require("shiny")) install.packages("shiny", dependencies = TRUE) 
if(!require("shinydashboard")) install.packages("shinydashboard", dependencies = TRUE)  
if(!require("shinyBS")) install.packages("shinyBS", dependencies = TRUE)  
if(!require("leaflet")) install.packages("leaflet", dependencies = TRUE) 
if(!require("BH")) install.packages("BH", dependencies = TRUE)  
if(!require("RCurl")) install.packages("RCurl", dependencies = TRUE) 
if(!require("RandomFieldsUtils")) install.packages("RandomFieldsUtils", dependencies = TRUE) 
if(!require("R.oo")) install.packages("R.oo", dependencies = TRUE) 
if(!require("R.methodsS3")) install.packages("R.methodsS3", dependencies = TRUE) 
if(!require("SpaDES")) install.packages("SpaDES", dependencies = TRUE) 
if(!require("markdown")) install.packages("markdown", dependencies = TRUE)  
if(!require("visNetwork")) install.packages("visNetwork", dependencies = TRUE) 
if(!require("rgexf")) install.packages("rgexf", dependencies = TRUE) 
if(!require("influenceR")) install.packages("influenceR", dependencies = TRUE) 
if(!require("DBI")) install.packages("DBI", dependencies = TRUE) 
if(!require("viridis")) install.packages("viridis", dependencies = TRUE) 
if(!require("bit")) install.packages("bit", dependencies = TRUE) 
if(!require("parallel")) install.packages("parallel", dependencies = TRUE)  
if(!require("devtools")) install.packages("devtools", dependencies = TRUE)  
if(!require("raster")) install.packages("raster", dependencies = TRUE) 
if(!require("rgeos")) install.packages("rgeos", dependencies = TRUE) 
if(!require("RSQLite")) install.packages("RSQLite", dependencies = TRUE) 
if(!require("magrittr")) install.packages("magrittr", dependencies = TRUE) 
if(!require("sp")) install.packages("sp", dependencies = TRUE)  
if(!require("dplyr")) install.packages("dplyr", dependencies = TRUE)  
if(!require("ggplot2")) install.packages("ggplot2", dependencies = TRUE) 
if(!require("maptools")) install.packages("maptools", dependencies = TRUE) 
if(!require("broom")) install.packages("broom", dependencies = TRUE) 
if(!require("ggvis")) install.packages("ggvis", dependencies = TRUE) 
if(!require("rgdal")) install.packages("rgdal", dependencies = TRUE) 
if(!require("grid")) install.packages("grid", dependencies = TRUE)  
if(!require("VGAM")) install.packages("VGAM", dependencies = TRUE)  
if(!require("data.table")) install.packages("data.table", dependencies = TRUE) 
if(!require("fpCompare")) install.packages("fpCompare", dependencies = TRUE) 

if (!require("RandomFieldsUtils")) install.packages("RandomFieldsUtils")
if (!require("RandomFields")) install.packages("RandomFields")
