---
title: "LandMine"
author: "Eliot McIntire"
date: "14 January 2017"
output:
  html_document: default
  pdf_document: default
---

# Overview

Landmine is a model created for simulating the natural range of variation for landscapes in the boreal forest.
Written in the 1990s (Andison 1996), it has been widely used by the public and the private sector for various purposes.
This `SpaDES` module is a rewrite of the fire component in native R.

## Current Differences

The current version has not been fully tested and compared with the original version, and there are currently several known differences:

- Fire sizes are taken from a Truncated Pareto distribution, resulting in numerous very small fires, and few large fires.
- Parameters have been not been fitted to the landscapes that are under study in the LandWeb project

# Known species

Landmine requires the following codes as inputs (the genus_spec form below), and converts and groups species as follows. Each of the species groups has its own Rate of Spread (ROS) for fire spreading:

* PINU

    * "Pinu_ban"
    * "Pinu_con" 
    * "Pinu_sp" 
* DECI

    * Betu_pap
    * Popu_bal
    * Popu_tre
    * Lari_lar
    
* PICE_MAR

    * Pice_mar
    
* PICE_GLA

    * Pice_gla
    
* ABIE

    * Abie_sp
    
    
# Usage

To run this Landmine module alone, from an R console, the following should work (*iff* raster inputs for `rstStudyRegion` and `rstFlammable` are available), assuming all R packages are available.
Paths will have be changed for a different user.

To deteremine which packages are used by `LandMine`, run `SpaDES::packages(module = "LandMine")`.

```{r module_usage, eval = FALSE}
library(igraph)
library(SpaDES)

workingDir <- file.path("~/GitHub/LandWeb")
moduleDir <- file.path(workingDir, "m") %>% checkPath()
inputDir <- file.path(workingDir, "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(workingDir, "outputs") %>% checkPath(create = TRUE)
cacheDir <- file.path(outputDir, "cache") %>% checkPath(create = TRUE)
times <- list(start = 0, end = 13)
parameters <- list(
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #LandMine = list(flushCachedRandomFRI = TRUE) 
)
modules <- list("LandMine")
objects <- list()
paths <- list(
  cachePath = cacheDir,
  modulePath = moduleDir,
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

spades(mySim, .plotInitialTime = times$start, progress = TRUE)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("LandMine", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

