---
title: "LBMR"
author: "Jean Marchal (jean.d.marchal@gmail.com)"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: default
  pdf_document: default
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## RMarkdown

RMarkdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in RMarkdown, see http://rmarkdown.rstudio.com/.

# Usage

# Usage
## Module parameters
Name|Default|Description
----|:--------------|---------------------------------------------------------------------
`formula`|`NA`|a formula describing the model to be fitted. Piece-wised terms can be specifed using `pw(variableName, knotName)`.
`family`|`negative.binomial`|a family function (must be wrapped with `quote()`) or a character string naming a family function. For additional details see `?family`.
`data`|`"dataFireSense_FrequencyFit"`|a character vector indicating the names of objects in the `simList` environment in which to look for variables present in the model formula. `data` objects should be data.frames. If variables are not found in `data` objects, they are searched in the `simList` environment.
`start`|`NULL`|optional starting values for the parameters to be estimated. Those are passed to `nlminb` and can be a single vector, or a list of vectors. In the latter case, only the best solution, that is, the one which minimizes the most the objective function, is kept.
`lb`|`NULL`|optional named list with up to three elements, 'coef', 'theta' and 'knots', specifying lower bounds for coefficients to be estimated. These must be finite and will be recycled if necessary to match `length(coefficients)`.
`ub`|`NULL`|optional named list with up to three elements, 'coef', 'theta' and 'knots', specifying upper bounds for coefficients to be estimated. These must be finite and will be recycled if necessary to match `length(coefficients)`.
`itermax`|`500`|integer defining the maximum number of iterations allowed (DEoptim optimizer).
`nTrials`|`500`|if start is not supplied, `nTrials` defines the number of trials, or searches, to be performed by the nlminb optimizer in order to find the best solution.
`nCores`|`1`|non-negative integer. Defines the number of logical cores to be used for parallel computation. The default value is 1, which disables parallel computing.
`trace`|`0`|non-negative integer. If > 0, tracing information on the progress of the optimization are printed every `trace` iteration. If parallel computing is enable, nlminb trace logs are written to disk. Log files are prefixed with 'fireSense_FrequencyFit_trace' followed by the subprocess pid. Default is 0, which turns off tracing.
`nlminb.control`|`list(iter.max = 5e3L,`<br>&emsp;&emsp;&emsp;`eval.max=5e3L`)|optional list of control parameters to be passed to the `nlminb` optimizer. See `?nlminb`.
`initialRunTime`|`start(simList)`|when to start this module? By default, the start time of the simulation.
`intervalRunModule`|`NA`|optional. Interval between two runs of this module, expressed in units of simulation time.
|||
library(magrittr)

inputDir <- file.path(dirname(tempdir()), "LBMR", "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(dirname(tempdir()), "LBMR", "outputs") 
times <- list(start = 0, end = 10)
parameters <- list(
  .globals = list(verbose = FALSE),
  LBMR = list(.plotInitialTime = NA)
  #.progress = list(type = "text", interval = 1), # for a progress bar
  ## If there are further modules, each can have its own set of parameters:
  #module1 = list(param1 = value1, param2 = value2),
  #module2 = list(param1 = value1, param2 = value2)
)
modules <- list("LBMR")
objects <- list(successionTimestep = 2)
paths <- list(
  cachePath = file.path(outputDir, "cache"),
  modulePath = file.path("."),
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

mySimOut <- spades(mySim, debug = TRUE)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("LBMR", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

