---
title: "CanadaWide_FireSense"
author: ""
date: "14 February 2018"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## R Markdown

R Markdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in R Markdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
#devtools::install_github("PredictiveEcology/reproducible@development")
devtools::install_github("ygc2l/webDatabases") # For fetching KNN layers from PFC repo

library(igraph)
library(SpaDES.core)
library(MASS)


library(magrittr) # for %>% pipe
library(SpaDES)
library(raster)

cachePath <- file.path("Boreal_FireSenseDataPrep", "cache")
moduleDir <- Cache(readline, paste0("Where is the module path? (e.g., ~/module, with no quotes).\n",
                                     "Press Enter to accept the path in getPaths()$modulePath: "),
                    cacheRepo = cachePath)
if(nchar(moduleDir)==0) moduleDir <- getPaths()$modulePath

inputDir <- file.path(moduleDir, "inputs") %>% reproducible::checkPath(create = TRUE)
outputDir <- file.path(moduleDir, "outputs")
cacheDir <- file.path(outputDir, "cache")

canadaMap <- Cache(getData, 'GADM', country = 'CAN', level = 1,
                   cacheRepo = cachePath, digestPathContent = FALSE) 
dev()
clearPlot()
Plot(canadaMap, speedup = 5, visualSqueeze = 0.9) # 5 seemed optimal
if(!exists("studyArea")) {
  message("Since there is no object called 'shpStudyRegionFull', please draw a study area with 10 points")
  severalrandompoints <- Cache(clickCoordinates, 10, cacheRepo = cachePath)
  if(startsWith(attr(severalrandompoints, "tags"), "cache")) message("Taking shpStudyRegionFull from Cache")
  studyArea <- SpatialPolygons(list(Polygons(list(Polygon(severalrandompoints$coords)), ID = 1)),
                               proj4string = crs(canadaMap))
}
Plot(studyArea, addTo = "canadaMap", col = "red")

inputDir <- file.path(moduleDir, "inputs") %>% reproducible::checkPath(create = TRUE)
outputDir <- file.path(moduleDir, "outputs")
times <- list(start = 0, end = 10)
parameters <- list(
  fireSense_FrequencyFit = list(
    formula = n_fires ~ broadLeafPc + needleLeafPc + otherPc - 1, 
    family = negative.binomial(1, link = "identity"),
    .runInitialTime = .1
  ),
  fireSense_FrequencyPredict = list(
    f = 1600#,    .runInitialTime = .2
  ),
  fireSense_SizeFit = list(
    formula = list(beta = size ~ broadLeafPc + otherPc,
                   theta = size ~ broadLeafPc + otherPc),
    a = 1#,    .runInitialTime = .3
  ),
  # fireSense_SizePredict = list(
  #   .runInitialTime = .4
  # ),
  fireSense_EscapeFit = list(
    formula = cbind(escaped, n_fires) ~ broadLeafPc + otherPc#,    .runInitialTime = .5
  ),
  # fireSense_EscapePredict = list(
  #   .runInitialTime = .6
  # ),
  fireSense_SpreadFit = list(
    formula = ~ fireSense_SizePredicted_Beta + fireSense_SizePredicted_Theta,
    lower = c(.01, .2, .1,  .3, .001, .001, .001),
    upper = c(.20, .5, 10,  4., .300, .300, .300),
    trace = 1#,    .runInitialTime = .7
  ),
  # fireSense_SpreadPredict = list(
  #   .runInitialTime = .8
  # ),
  fireSense = list(
    mapping = list(
      ignitionProb = "fireSense_FrequencyPredicted",
      escapeProb = "fireSense_EscapePredicted",
      spreadProb = "fireSense_SpreadPredicted"
    )#,    .runInitialTime = .9
  )
)
modules <- list("CanadaWide_FireSense")
objects <- list("studyArea" = studyArea)
paths <- list(
  cachePath = cacheDir,
  modulePath = moduleDir,
  inputPath = inputDir,
  outputPath = outputDir
)

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths, loadOrder = c("Boreal_FireSenseDataPrep", "fireSense_FrequencyFit", "fireSense_FrequencyPredict", "fireSense_SizeFit", "fireSense_SizePredict", "fireSense_EscapeFit", "fireSense_EscapePredict", "fireSense_SpreadFit", "fireSense_SpreadPredict", "fireSense"))

spades(mySim, debug = TRUE)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("CanadaWide_FireSense", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

