# Model outputs {-}

- burnSummaries module ... (TODO)
- LandMine module ... (TODO)
- LandWeb_outputs module ... (TODO)
- LandWeb_summary module ... (TODO)
- timeSinceFire module ... (TODO)

Previously-run model outputs are available to download for authorized users, and are described below.

## Currently Selected Spatial Area

- Currently selected reporting polygon (`.shp`)

## Large Patches Data for study region

- Large Patches Data (`.csv`)
- Large patches histograms (`.png`)

## Leading Vegetation Cover Data for study region

- Leading Vegetation Cover Data (`.csv`)
- Leading Vegetation Cover histograms (`.png`)
- Leading Vegetation Cover boxplots (`.png`)

## Simulation Rasters (cropped to study region)

- Flammability maps (`.grd`)
- Time Since Fire maps (`.tif`)
- Vegetation type maps (`.grd`, `.tif`)

## Additional R Data Files (advanced users)

- Simulation data files (`.RData`, `.rds`)

The downloaded outputs are bundled into a zip file (*e.g.*, `LandWeb_v2.0.0_2019-09-23.zip`) with the following directory and file structure:

```
LandWeb_v2.0.0_2019-09-23/
 |_ boxplots/
     |_ leading_*.csv
 |_ histograms/
     |_ largePatches/
         |_ 100/
         |_ 500/
         |_ 1000/
         |_ 5000/
     |_ leading/
     |_ largePatches_*.csv
 |_ polygons/
 |_ rasters/
     |_ rstTimeSinceFire_*.tif
     |_ vegTypeMap_*.tif*
 |_ INFO.md
 |_ README.md
 |_ simulationOutput_*.rds
```
