---
title: "landWeb_LBMRDataPrep"
author: ""
date: "28 October 2016"
output: pdf_document
---

# Overview

Provide an overview of what the module does / how to use the module.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## RMarkdown

RMarkdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in RMarkdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
rm(list = ls())
library(igraph)
library(SpaDES)
library(raster)
canadamap <- shapefile("~/GIS DataBase/Canada/Canada.shp")
dev(4)
clearPlot()
Plot(canadamap)
severalrandompoints <- clickCoordinates(10)
studyarea <- SpatialPolygons(list(Polygons(list(Polygon(severalrandompoints$coords)), ID = 1)),
                             proj4string = crs(canadamap))
inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)
outputDir <- file.path(tempdir(), "outputs")
times <- list(start = 0, end = 10)
parameters <- list()
modules <- list("landWeb_LBMRDataPrep")
# studyarea <- shapefile(file.path(".", "landWeb_LBMRDataPrep", "data", "shpLandWEB.shp"))
objects <- list("studyArea" = studyarea,
                "useCache" = TRUE,
                "successionTimestep" = 2)
paths <- list(
  cachePath = file.path("~", "landWeb_LBMRDataPrep", "cache"),
  modulePath = file.path("."),
  inputPath = inputDir,
  outputPath = outputDir
)
mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)

simulation <- spades(mySim)




```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("landWeb_LBMRDataPrep", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

