---
title: "landWebDataPrep"
author: "Module Author"
date: "11 August 2016"
output: pdf_document
---

# Overview

This module is higher level data preparation for fire module and veg module, its outputs creates inputs for initBaseMaps module for fire and landWeb_LBMRDataPrep module for veg.

Module documentation should be written so that others can use your module.
This is a template for module documentation, and should be changed to reflect your module.

## RMarkdown

RMarkdown syntax allows R code, outputs, and figures to be rendered in the documentation.

For help writing in RMarkdown, see http://rmarkdown.rstudio.com/.

# Usage

```{r module_usage}
library(SpaDES)
library(magrittr)
library(raster)
library(rgdal)

inputDir <- file.path(tempdir(), "inputs") %>% checkPath(create = TRUE)

times <- list(start = 0, end = 30)

if (Sys.info()[1] == "Linux") {
  curDir <- file.path("~", "Documents", "GitHub", "LandWeb")
} else {
  curDir <- file.path("~", "GitHub", "LandWeb")
}
paths <- if (Sys.info()[["user"]] == "achubaty") {
  list(
    cachePath = file.path("~/SpaDES/cache"),
    modulePath = curDir,
    inputPath = inputDir,
    outputPath = file.path("~/SpaDES/outputs")
  )
} else {
  list(
    cachePath = file.path("~", "CachedFiles"),
    modulePath = curDir,
    inputPath = inputDir,
    outputPath = file.path("~", "simulationOutput")
  )
}

f <- file.path(curDir, "landWebDataPrep", "data", "shpLandWEB.shp")
if (!file.exists(f)) {
  ## TO DO: need to download if doesn't exist
}
shpStudyRegion <- Cache(shapefile, f, cacheRepo = paths$cachePath)
shpStudyRegion$fireReturnInterval <- shpStudyRegion$LTHRC
shpStudyRegion@data <- shpStudyRegion@data[, !(names(shpStudyRegion) %in% "ECODISTRIC")]

r <- file.path(curDir,"landWebDataPrep", "data",  "NFI_MODIS250m_kNN_Structure_Biomass_TotalLiveAboveGround_v0.tif")
if (!file.exists(r)) {
  ## TO DO: need to download if doesn't exist
}
biomassMap <- raster(r)
studyArea <- "SMALL"
if (studyArea == "SMALL") {
  smallExt <- new("Extent" , xmin = -983660, xmax = -899973, ymin = 8007529, ymax = 8085986)
  shpStudyRegion2 <- spTransform(shpStudyRegion, crs(biomassMap))
  shpStudyRegion <- crop(shpStudyRegion2, smallExt)
} else if (studyArea == "medium"){
  shpStudyRegionOrig <- spTransform(shpStudyRegion, crs(biomassMap))
  set.seed(2)#set.seed(5567913)
  areaKm2 <- 80000#700000#2000#600000#too big for laptop
  minX <- -1202250.2
  maxX <- minX+sqrt(areaKm2*1e6)
  minY <- 7008877-1.6e5
  maxY <- minY+sqrt(areaKm2*1e6)
  meanY <- mean(c(minY, maxY))
  
  # Add random noise to polygon
  xAdd <- round(runif(1,-5e5,1.5e6))
  yAdd <- round(runif(1,1e5,5e5))-xAdd/2
  nPoints <- 20
  betaPar=0.6
  X = c(jitter(sort(rbeta(nPoints, betaPar, betaPar)*(maxX-minX)+minX)),
        jitter(sort(rbeta(nPoints, betaPar, betaPar)*(maxX-minX)+minX, decreasing = TRUE)))
  Y = c(jitter(sort(rbeta(nPoints/2, betaPar, betaPar)*(maxY-meanY)+meanY)),
        jitter(sort(rbeta(nPoints, betaPar, betaPar)*(maxY-minY)+minY, decreasing = TRUE)),
        jitter(sort(rbeta(nPoints/2, betaPar, betaPar)*(meanY-minY)+minY)))
  
  Sr1 <- Polygon(cbind(X+xAdd,Y+yAdd))
  Srs1 = Polygons(list(Sr1), "s1")
  inputMapPolygon <- SpatialPolygons(list(Srs1), 1L)
  crs(inputMapPolygon) <- crs(biomassMap)
  dev(4)
  clearPlot()
  Plot(shpStudyRegionOrig)
  Plot(inputMapPolygon, addTo = "shpStudyRegionOrig", col = "red")
  shpStudyRegion <- intersect(shpStudyRegionOrig, inputMapPolygon)
}

#modules <- list("landWebDataPrep", "initBaseMaps", "fireDataPrep", "fireNull", "landWeb_LBMRDataPrep", "LBMR")

#modules <- list("landWebDataPrep", "initBaseMaps", "fireDataPrep", "fireNull")
#modules <- list("landWebDataPrep", "initBaseMaps", "LandMine")

modules <- list("landWebDataPrep", "initBaseMaps", "LandMine", "landWeb_LBMRDataPrep", "LBMR", "timeSinceFire", "LandWebOutput")

fireModules <- list("landWebDataPrep", "initBaseMaps", "LandMine", "timeSinceFire", "LandWebOutput")

successionTimestep <- 2

objects <- list("shpStudyRegionX" = shpStudyRegion,
                "successionTimestep" = successionTimestep,
                "summaryPeriod" = c(10, 20))

parameters <- list(
  fireNull = list(burnInitialTime = 1, returnInterval = 1, .statsInitialTime = 1),
  LandWebOutput = list(summaryInterval = 2),
  LBMR = list(.plotInitialTime = times$start),
  initBaseMaps = list(.useCache = TRUE)
)
library()
for(indimodule in modules){
  datapath <- file.path(paths$modulePath, unlist(indimodule), "data")
  allfiles <- dir(datapath)
  ziptarfiles <- allfiles[tools::file_ext(allfiles) %in% c("tar", "zip")]
  lapply(ziptarfiles, function(s) file.remove(file.path(datapath, s)))
}

mySim <- simInit(times = times, params = parameters, modules = modules,
                 objects = objects, paths = paths)


## ensure all required packages are installed
needsInstall <- sapply(packages(mySim), function(pkg) {
  !require(pkg, character.only = TRUE, quietly = TRUE)
})
if (any(needsInstall)) {
  stop("Some required packages are missing. Use the following to install them:\n",
       "  install.packages(names(which(needsInstall)))")
}

## don't use Rstudio graphics
dev.useRSGD(FALSE)

##run the model
a <- spades(Copy(mySim), debug = TRUE)
```

# Events

Describe what happens for each event type.

## Plotting

Write what is plotted.

## Saving

Write what is saved.

# Data dependencies

## Input data

How to obtain input data, and a description of the data required by the module.
If `sourceURL` is specified, `downloadData("landWebDataPrep", "path/to/modules/dir")` may be sufficient.

## Output data

Description of the module outputs.

# Links to other modules

Describe any anticipated linkages to other modules.

